name: Dag Request
description: Data pipeline request
title: "DAG: "
labels: [enhancement]

body:
  - type: dropdown
    id: department
    attributes:
      label: Department
      description: Please select the department that would like to request a dag.
      options:
        - Finance
        - Ticket
        - Marketing
        - Data
        - Web
        - Management
        - Sales
        - HR
        - Legal 

  - type: textarea
    id: description
    attributes:
      label: Dag Description
      description: >
        Please describe the purpose of the dag, the result should be, and dag info refered to the place holder.
      placeholder: >
        I want a dag that will send a report to management every month showing the total sales per store.
        Dag request:
          - Frequency: Daily
          - Parameters (optional): Start Date, End Date
          - Email Recipients (optional): management@richmond.com
          - Attachments (optional): Sales Report
          - Need to save the data to database/s3/other storage? (optional): Yes, save to postgres.
          - What's the SLA? (optional): 99.9% uptime.
          - How late can the data be? (optional): 1 hour.

    validations:
      required: true
  - type: textarea
    id: data_description
    attributes:
      label: Data description
      description: >
        Please describe what data is needed. Contain data source and short description is encouraged.
      placeholder: >
        Cowell:
          - TRGRUP: group leave date and name
          - TRGPAX: GAR_AM from each passenger

  - type: textarea
    id: logic_description
    attributes:
      label: Logic description
      description: >
        If some specific logic are applied, please describe it or refer to wiki or other document.
      placeholder: >
        Use account number instead of tax ID for companies, as not all companies have a tax ID.
