name: Feature Request
description: Suggest an idea for airflow
title: "ENH: "
labels: [enhancement]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Feature Type
      description: Please check what type of feature request you would like to propose.
      options:
        - label: >
            Adding new functionality
        - label: >
            Changing existing functionality
        - label: >
            Removing existing functionality
  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: >
        Please describe what problem the feature would solve, e.g. "I wish I could ..."
      placeholder: >
        I wish there was a ODBCHook to connect to Cowell
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: >
        Please describe how the new feature would be implemented, using psudocode if relevant.
      placeholder: >
        Add a new plugin to airflow to connect to Cowell

        class ODBCHook(BaseHook):
            def __init__(self, conn_id: str):
                self.conn_id = conn_id

            def get_conn(self):
                return self.get_connection(self.conn_id).get_conn()
    validations:
      required: true

  - type: textarea
    id: alternative
    attributes:
      label: Alternative Solutions
      description: >
        Please describe any alternative solution (existing functionality, 3rd party package, etc.)
        that would satisfy the feature request.
      placeholder: >
        Write a custom function to return a ODBCHook when possible.

        def to_odbc_hook(self, conn_id: str):
            return ODBCHook(conn_id)
            
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: >
        Please provide any relevant GitHub issues, code examples or references that help describe and support
        the feature request.